import type { Restroom } from "./types";

/**
 * Built-in restrooms used when no Supabase project is configured yet, so the
 * whole app is browsable before you create any cloud accounts. Real, well-known
 * Manhattan locations — coordinates are approximate and these are NOT written
 * to the database. Once NEXT_PUBLIC_SUPABASE_URL is set, this is never read.
 */
export const SAMPLE_RESTROOMS: Restroom[] = [
  {
    id: "sample-bryant-park",
    name: "Bryant Park Restrooms",
    kind: "park",
    lat: 40.7536,
    lng: -73.9832,
    isFree: true,
    requiresPurchase: false,
    isAccessible: true,
    hasChangingTable: true,
    hours: "7am–10pm",
    address: "Bryant Park, behind the library",
    notes: "Famously clean, with fresh flowers. Expect a line at lunchtime.",
    source: "user",
    createdAt: "2026-01-04T12:00:00Z",
    distanceM: null,
    up: 14,
    down: 0,
    score: 14,
    confidence: "confirmed",
  },
  {
    id: "sample-grand-central",
    name: "Grand Central Terminal",
    kind: "transit",
    lat: 40.7527,
    lng: -73.9772,
    isFree: true,
    requiresPurchase: false,
    isAccessible: true,
    hasChangingTable: true,
    hours: "5:30am–2am",
    address: "89 E 42nd St, lower dining concourse",
    notes: "Down by the food court. Open very early and very late.",
    source: "user",
    createdAt: "2026-01-06T12:00:00Z",
    distanceM: null,
    up: 9,
    down: 0,
    score: 9,
    confidence: "confirmed",
  },
  {
    id: "sample-nypl",
    name: "New York Public Library",
    kind: "library",
    lat: 40.7532,
    lng: -73.9822,
    isFree: true,
    requiresPurchase: false,
    isAccessible: true,
    hasChangingTable: false,
    hours: "10am–6pm, closed Sundays",
    address: "476 5th Ave",
    notes: "Ground floor, past the security desk. No purchase, no questions.",
    source: "user",
    createdAt: "2026-01-08T12:00:00Z",
    distanceM: null,
    up: 6,
    down: 0,
    score: 6,
    confidence: "confirmed",
  },
  {
    id: "sample-whole-foods-bryant",
    name: "Whole Foods Bryant Park",
    kind: "store",
    lat: 40.7519,
    lng: -73.9835,
    isFree: true,
    requiresPurchase: false,
    isAccessible: true,
    hasChangingTable: true,
    hours: "7am–10pm",
    address: "1095 6th Ave, upstairs seating",
    notes: "Upstairs by the seating area. Nobody checks for a receipt.",
    source: "user",
    createdAt: "2026-02-11T12:00:00Z",
    distanceM: null,
    up: 4,
    down: 1,
    score: 3,
    confidence: "confirmed",
  },
  {
    id: "sample-penn-moynihan",
    name: "Moynihan Train Hall",
    kind: "transit",
    lat: 40.7506,
    lng: -73.9935,
    isFree: true,
    requiresPurchase: false,
    isAccessible: true,
    hasChangingTable: true,
    hours: "5am–1am",
    address: "351 W 31st St",
    notes: "Newest and cleanest option near Penn Station.",
    source: "user",
    createdAt: "2026-02-02T12:00:00Z",
    distanceM: null,
    up: 11,
    down: 0,
    score: 11,
    confidence: "confirmed",
  },
  {
    id: "sample-madison-sq-park",
    name: "Madison Square Park",
    kind: "park",
    lat: 40.7422,
    lng: -73.9878,
    isFree: true,
    requiresPurchase: false,
    isAccessible: true,
    hasChangingTable: false,
    hours: "8am–8pm (seasonal)",
    address: "Madison Ave & E 24th St",
    notes: "Near the dog run. Closes earlier in winter.",
    source: "user",
    createdAt: "2026-03-01T12:00:00Z",
    distanceM: null,
    up: 3,
    down: 0,
    score: 3,
    confidence: "confirmed",
  },
  {
    id: "sample-hudson-yards",
    name: "The Shops at Hudson Yards",
    kind: "mall",
    lat: 40.7539,
    lng: -74.0022,
    isFree: true,
    requiresPurchase: false,
    isAccessible: true,
    hasChangingTable: true,
    hours: "10am–8pm",
    address: "20 Hudson Yards, levels 2–5",
    notes: "Multiple floors, rarely a wait above level 3.",
    source: "user",
    createdAt: "2026-03-14T12:00:00Z",
    distanceM: null,
    up: 5,
    down: 0,
    score: 5,
    confidence: "confirmed",
  },
  {
    id: "sample-starbucks-times-sq",
    name: "Starbucks Times Square",
    kind: "cafe",
    lat: 40.7566,
    lng: -73.9863,
    isFree: false,
    requiresPurchase: true,
    isAccessible: false,
    hasChangingTable: false,
    hours: "6am–11pm",
    address: "1500 Broadway",
    notes: "Door code is on the receipt, so you need to buy something.",
    source: "user",
    createdAt: "2026-04-02T12:00:00Z",
    distanceM: null,
    up: 2,
    down: 1,
    score: 1,
    confidence: "unverified",
  },
  {
    id: "sample-highline-14",
    name: "High Line at 14th St",
    kind: "park",
    lat: 40.7424,
    lng: -74.0079,
    isFree: true,
    requiresPurchase: false,
    isAccessible: true,
    hasChangingTable: true,
    hours: "7am–10pm (seasonal)",
    address: "High Line, near the 14th St passage",
    notes: "The only restroom on the High Line — plan ahead.",
    source: "user",
    createdAt: "2026-04-19T12:00:00Z",
    distanceM: null,
    up: 7,
    down: 0,
    score: 7,
    confidence: "confirmed",
  },
  {
    id: "sample-washington-sq",
    name: "Washington Square Park",
    kind: "park",
    lat: 40.7308,
    lng: -73.9973,
    isFree: true,
    requiresPurchase: false,
    isAccessible: true,
    hasChangingTable: false,
    hours: "8am–8pm",
    address: "Washington Square Park, southwest corner",
    notes: "Southwest corner near the chess tables.",
    source: "user",
    createdAt: "2026-05-05T12:00:00Z",
    distanceM: null,
    up: 3,
    down: 1,
    score: 2,
    confidence: "confirmed",
  },
  {
    id: "sample-union-sq",
    name: "Union Square Park",
    kind: "park",
    lat: 40.7359,
    lng: -73.9911,
    isFree: true,
    requiresPurchase: false,
    isAccessible: false,
    hasChangingTable: false,
    hours: "Varies",
    address: "Union Square, north end",
    notes: "Hit or miss — often closed for cleaning.",
    source: "user",
    createdAt: "2026-05-21T12:00:00Z",
    distanceM: null,
    up: 1,
    down: 1,
    score: 0,
    confidence: "unverified",
  },
  {
    id: "sample-closed-example",
    name: "Herald Square Public Toilet",
    kind: "public",
    lat: 40.7488,
    lng: -73.9884,
    isFree: true,
    requiresPurchase: false,
    isAccessible: true,
    hasChangingTable: false,
    hours: "Unknown",
    address: "Herald Square",
    notes: "Reported permanently closed by several people.",
    source: "user",
    createdAt: "2026-05-30T12:00:00Z",
    distanceM: null,
    up: 0,
    down: 3,
    score: -3,
    confidence: "likely_gone",
  },
];
